name: API Workflow
on:
  push:
    paths:
      - 'data.json'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  process-data:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Process Data
        run: |
          if [ ! -f data.json ]; then
            echo '{"workoutData":{}}' > data.json
          fi
